/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.example;

import statemachine.configuration.StateMachineConfiguration;

public class FlightStateMachineExample {

    public static void main(String[] args) {
        StateMachineConfiguration
    }
}
