/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.example;

import org.junit.jupiter.api.Test;

class FlightStateMachineExampleTest {
    @Test void appHasAGreeting() {
    }
}
