/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sfsm


import org.junit.jupiter.api.Test
import sfsm.State.*
import statemachine.configuration.DefaultStateMachineConfiguration
import statemachine.guard.ofPredicate
import statemachine.transition.DefaultTransition

class StateMachineCoreTest {

    @Test
    fun testStateMachineConstruction() {
        val config = DefaultStateMachineConfiguration<State, Trigger>()
        val positiveGuard = ofPredicate<State, Trigger> { true }

//        config.initial(INITIAL)
//        config.states(INITIAL, STATE_A, STATE_B, TERMINAL_STATE)
//
//        config.transitions(DefaultTransition(INITIAL, STATE_A, MOVE_TO_A))

    }

}

enum class State {
    INITIAL, STATE_A, STATE_B, TERMINAL_STATE
}

enum class Trigger {
    MOVE_TO_A, MOVE_TO_B, END
}
