/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.flight;

import flight.FlightStateMachineConfiguration;
import org.junit.jupiter.api.Test;
import statemachine.StateMachine;
import statemachine.factory.DefaultStateMachineFactory;
import flight.FlightStateMachineConfiguration.*;

import static flight.FlightStateMachineConfiguration.FlightState.BOARDING;
import static org.junit.jupiter.api.Assertions.assertEquals;

class FlightStateMachineApplicationTest {
    @Test void testFlight() {
        FlightStateMachineConfiguration flightStateMachineConfiguration = new FlightStateMachineConfiguration();
        DefaultStateMachineFactory<FlightState, FlightTrigger> factory = new DefaultStateMachineFactory<>(flightStateMachineConfiguration);

        StateMachine<FlightState, FlightTrigger> sm = factory.create("TEST_SM");
        assertEquals(BOARDING,  sm.getState().getId());
    }
}
