name: PR update
on:
  pull_request:
    types: [opened, reopened, edited]
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run Gradle Wrapper - build
        run: ./gradlew build
          
          
