name: PR update
on:
  pull_request:
    types: [opened, reopened, edited]

  workflow_dispatch:

jobs:
  extract-pr-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine required version bump from PR description
        id: determine-bump
        run: |          
          chmod +x .github/determine_version_bump.sh
          DETERMINED_BUMP=$(./.github/determine_version_bump.sh "${{ github.event.pull_request.body }}")
          echo "Determined bump is $DETERMINED_BUMP"
          echo "BUMP=$(echo $DETERMINED_BUMP)" >> $GITHUB_ENV
      - name: Determine latest tag/version
        id: determine-latest-version
        run: |
          chmod +x .github/determine_latest_tag.sh
          LATEST_TAG=$(./.github/determine_latest_tag.sh)
          echo "LATEST_TAG=$LATEST_TAG" >> "$GITHUB_ENV"
          
          
