name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
env:
  VERSION: v${{ github.event.inputs.version }}
  SEMVER_VERSION: ${{ github.event.inputs.version }}
  ARTIFACT_ZIP_NAME: ${{ vars.GROUP }}-${{ vars.CORE_ARTIFACT_ID }}-${{ github.event.inputs.version }}-bundle.zip
  JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
  JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
  JRELEASER_MAVENCENTRAL_SONATYPE_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_PASSWORD }}
  JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME }}
  JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}


jobs:
  publish_version:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: build statemachine-core
        run: ./gradlew statemachine-core:build

      - name: create publication for statemachine-core
        run: ./gradlew statemachine-core:publish -Pversion=${{ env.SEMVER_VERSION }}

      - name: Deploy to Maven Central
        run: ./gradlew statemachine-core:jreleaserDeploy -Pversion=${{ env.SEMVER_VERSION }}

      - name: Upload artifacts zip
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{ vars.CORE_DEPLOYMENTS_PATH }}/${{ env.ARTIFACT_ZIP_NAME }}
          name: ${{ env.ARTIFACT_ZIP_NAME }}

  create_release:
    needs: publish_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download previously generated artifacts ZIP
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_ZIP_NAME }}

      - name: Tag latest commit with new version
        id: tag_commit
        run: |
          git config --global user.email "${{ secrets.AUTHOR_EMAIL }}"
          git config --global user.name "${{ secrets.AUTHOR_NAME }}"
          git tag -a "${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
          git push origin --tags

      - name: Verify tag exists
        run: |
          git fetch --tags
          if ! git rev-parse "${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag $VERSION does not exist."
            exit 1
          fi

      - name: Create draft GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.VERSION }} ${{ env.ARTIFACT_ZIP_NAME }} \
            --title "Release ${{ env.VERSION }}" \
            --notes-from-tag \
            --draft

