name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

permissions:
  actions: write
  id-token: write
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update VERSION file with new version
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ github.event.inputs.version }} > VERSION
          git add VERSION
          git config --global user.email "${{ secrets.AUTHOR_EMAIL }}"
          git config --global user.name "${{ secrets.AUTHOR_NAME }}"
          git commit -a -m "Setting release version: ${{ github.event.inputs.version }}"
          git tag -a "v${{ github.event.inputs.version }}" -m "Release version ${{ github.event.inputs.version }}"
          git push origin master
