name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Tag latest commit with new version
        id: tag_commit
        run: |
          git config --global user.email "${{ secrets.AUTHOR_EMAIL }}"
          git config --global user.name "${{ secrets.AUTHOR_NAME }}"
          git commit -a -m "Setting release version: ${{ github.event.inputs.version }}"
          VERSION="v${{ github.event.inputs.version }}"
          git tag -a "v${{ github.event.inputs.version }}" -m "Release version ${{ github.event.inputs.version }}"
          git push origin --tags
          echo "VERSION=VERSION" >> "$GITHUB_OUTPUT"
      - name: build statemachine-core
        env:
          VERSION: ${{ steps.tag_commit.outputs.VERSION }}
        run: ./gradlew statemachine-core:build
      - name: create publication for statemachine-core
        run: ./gradlew statemachine-core:publish -Pversion ${VERSION}
      - name: create publication for statemachine-core
        run: ./gradlew statemachine-core:publish -Pversion ${VERSION}
      - name: release publication
        run: ./gradlew statemachine-core:publish -Pversion ${VERSION}
      - name: Deploy to Maven Central
        run: ./gradlew statemachine-core:jreleaserDeploy --dry-run

          
          
