name: CI
on:
  pull_request_target:
    types:
      - closed
  workflow_dispatch:

jobs:
  pr-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine required version bump from PR description
        id: determine-bump
        run: |
          chmod +x .github/determine_version_bump.sh
          DETERMINED_BUMP=$(./.github/determine_version_bump.sh "${{ github.event.pull_request.body }}")
          echo "BUMP=$(echo $DETERMINED_BUMP)" >> $GITHUB_ENV

      - name: Bump latest version
        if: ${{ env.BUMP != "" }}
        id: bump-latest-version
        run: |
          CURRENT_VERSION = $(cat VERSION)
          echo "Performing a ${{ env.BUMP }} bump for version ${{ CURRENT_VERSION }}"
          chmod +x .github/version_bumper.sh
          
          BUMPED_VERSION=$(./.github/version_bumper.sh ${{ CURRENT_VERSION }} ${{ env.BUMP }})
          echo "CURRENT_VERSION=CURRENT_VERSION" >> "$GITHUB_ENV"
          echo "BUMPED_VERSION=$BUMPED_VERSION" >> "$GITHUB_ENV"
          echo "next version is $BUMPED_VERSION"
      - name: Tag Commits
        if: ${{ env.BUMP != "" }}
        run: |
          if [[ ! "${BUMPED_VERSION}" =~ ^v ]]; then
            BUMPED_VERSION="v${BUMPED_VERSION}"
          fi

          if [[ ${{ vars.BETA == 'true' }} ]]; then
            BUMPED_VERSION="${BUMPED_VERSION}-BETA"
          fi
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "${{ BUMPED_VERSION }}" -m "Automatically tagged by GitHub Action"
          git push origin --tags
