name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Get the latest version number
      - name: Read current version
        id: get-version
        run: |
          current_version=$(git tag --sort=-v:refname --list "v[0-9]*" | head -n 1)
          echo "::set-output name=version::$current_version"
      # Get the required version bump (Major, minor or Patch) according to the PR description
      - name: Determine version bump
        id: determine-bump
        run: |
          chmod +x .github/determine_version_bump.sh
          bump=$(./.github/determine_version_bump.sh)
          echo "::set-output name=bump::$bump"
      # Do version bump
      - name: Bump the current version
        id: version-bump
        run: |
          chmod +x .github/version_bumper.sh
          output=$(./.github/version_bumper.sh ${{ steps.get-version.outputs.version }} ${{ steps.get-version.outputs.bump }})
          echo "::set-output name=version::$output"
      # Runs a set of commands using the runners shell
      - name: Tag Commits
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ steps.version-bump.outputs.version }}" -m "Automatically tagged by GitHub Action"
          git push origin --tags
